behaviors:
  MLTrader:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 0.8
        gamma: 0.99
      gail:
        strength: 1.0
        demo_path: Demos/DobbyDemo.demo
    behavioral_cloning:
      strength: 0.8
      demo_path: Demos/DobbyDemo.demo
    checkpoint_interval: 20000
    max_steps: 50000
    time_horizon: 64
    summary_freq: 50000